// src/app/api/events/[id]/memories/stories/route.ts
//
// Lists "Memory Stories" (anniversary reminders) generated by the daily
// cron (src/app/api/cron/stories/route.ts) for this event, and lets the
// host mark one as viewed. Read-only aside from the viewed_at PATCH.

import { z } from "zod"
import { defineRoute, ok, fail } from "@/lib/api/handler"
import { createServiceClient } from "@/lib/supabase/server"

const paramsSchema = z.object({ id: z.string().uuid() })
const patchBodySchema = z.object({ story_id: z.string().uuid() })

export const GET = defineRoute<unknown, unknown, { id: string }>({
  method: "GET",
  requireAuth: true,
  handler: async ({ params, auth }) => {
    const parsedParams = paramsSchema.safeParse(params)
    if (!parsedParams.success) return fail("VALIDATION_ERROR", "Invalid event ID", 422)
    const eventId = parsedParams.data.id

    const supabase = await createServiceClient()
    const { data: eventRow, error: eventErr } = await supabase.from("events").select("id, host_id").eq("id", eventId).single()
    if (eventErr || !eventRow) return fail("NOT_FOUND", "Event not found", 404)
    if (eventRow.host_id !== auth.user!.id) return fail("FORBIDDEN", "You don't have access to this event", 403)

    const { data, error } = await supabase
      .from("event_stories")
      .select("id, milestone_days, title, cover_photo_id, viewed_at, created_at")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false })

    if (error) return ok({ stories: [] })
    return ok({ stories: data ?? [] })
  },
}).GET

export const PATCH = defineRoute<z.infer<typeof patchBodySchema>, unknown, { id: string }>({
  method: "PATCH",
  body: patchBodySchema,
  requireAuth: true,
  handler: async ({ body, params, auth }) => {
    const parsedParams = paramsSchema.safeParse(params)
    if (!parsedParams.success) return fail("VALIDATION_ERROR", "Invalid event ID", 422)
    const eventId = parsedParams.data.id

    const supabase = await createServiceClient()
    const { data: eventRow, error: eventErr } = await supabase.from("events").select("id, host_id").eq("id", eventId).single()
    if (eventErr || !eventRow) return fail("NOT_FOUND", "Event not found", 404)
    if (eventRow.host_id !== auth.user!.id) return fail("FORBIDDEN", "You don't have access to this event", 403)

    const { error } = await supabase
      .from("event_stories")
      .update({ viewed_at: new Date().toISOString() })
      .eq("id", body.story_id)
      .eq("event_id", eventId)

    if (error) return fail("STORY_UPDATE_FAILED", "Could not mark story as viewed", 500)
    return ok({ success: true })
  },
}).PATCH
