// src/lib/integrations/summary-pdf.ts
//
// Renders the Event Summary as a downloadable one-pager (summary.pdf) using
// jsPDF — pure JS, no native binaries, no headless-browser/Puppeteer
// dependency, so it fits the same "no extra backend services" constraint as
// the rest of Snapsy Memories. White background by design (this is a
// printable/shareable document, unlike the in-app dark theme).

import "server-only"
import { jsPDF } from "jspdf"
import type { EventSummaryStats } from "./memories"
import { formatBytes, formatHour } from "./memories"

const MAUVE = "#A468A0"
const INK = "#211B22"
const MUTED = "#6B6470"

export interface SummaryPdfInput {
  eventName: string
  eventDate: string | null
  stats: EventSummaryStats
}

export function renderSummaryPdf({ eventName, eventDate, stats }: SummaryPdfInput): Buffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 48

  // Header
  doc.setFillColor(MAUVE)
  doc.rect(0, 0, pageWidth, 110, "F")
  doc.setTextColor("#FFFFFF")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(24)
  doc.text("Snapsy Memories", margin, 48)
  doc.setFontSize(14)
  doc.setFont("helvetica", "normal")
  doc.text(`${eventName} — Event Summary`, margin, 72)
  if (eventDate) {
    doc.setFontSize(10)
    doc.text(new Date(eventDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), margin, 90)
  }

  // Stat grid — 2 columns x 4 rows
  const cards: Array<{ label: string; value: string }> = [
    { label: "Photos", value: String(stats.photos) },
    { label: "Videos", value: String(stats.videos) },
    { label: "Voice Notes", value: String(stats.voiceNotes) },
    { label: "Guests", value: String(stats.guests) },
    { label: "Reactions", value: String(stats.totalReactions) },
    { label: "Comments", value: String(stats.totalComments) },
    { label: "Storage Used", value: formatBytes(stats.storageBytes) },
    { label: "Peak Upload Time", value: formatHour(stats.peakUploadHour) },
  ]

  const gridTop = 150
  const colWidth = (pageWidth - margin * 2 - 20) / 2
  const rowHeight = 64
  cards.forEach((card, i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    const x = margin + col * (colWidth + 20)
    const y = gridTop + row * (rowHeight + 14)

    doc.setDrawColor("#E5DFE3")
    doc.setFillColor("#FAF7F9")
    doc.roundedRect(x, y, colWidth, rowHeight, 8, 8, "FD")

    doc.setTextColor(MAUVE)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(22)
    doc.text(card.value, x + 16, y + 32)

    doc.setTextColor(MUTED)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)
    doc.text(card.label.toUpperCase(), x + 16, y + 50)
  })

  // Most active uploader callout
  const calloutY = gridTop + 4 * (rowHeight + 14) + 10
  if (stats.mostActiveUploader) {
    doc.setTextColor(INK)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(12)
    doc.text(`Most Active Guest: ${stats.mostActiveUploader}`, margin, calloutY)
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setTextColor(MUTED)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.text("Generated by Snapsy — snapsy-events.vercel.app", margin, pageHeight - 32)

  const out = doc.output("arraybuffer")
  return Buffer.from(out)
}
